import Head from 'next/head';
import MyCalendar from './../components/MyCalendar';
import Image from 'next/image';
import { useSession } from 'next-auth/react';
import Login from './login';

export default function Home() {
  const { data: session, status } = useSession();

  return status === 'authenticated' ? (
    <div className="h-full overflow-hidden">
      <Head>
        <title>다모임</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyCalendar session={session} />
    </div>
  ) : (
    <Login />
  );
}
